### ISSUE TITLE
유저 상태 전역으로 관리

### ISSUE THREAD

**Issue by page1597** [TEAM-MUNA/muna#26]
## 💼 작업 설명

현재 로그인한 유저의 상태와 정보를 전역으로 관리한다.

## ✅ To-do

- [x] Firebase의 onAuthStateChanged 함수 사용 (유저 상태 감지)
- [x] 현재 로그인한 사용자 가져오기 (getDoc)
- [x] redux-toolkit 사용해서 현재 로그인한 사용자 전역으로 저장 (authSlice의 setUser 추가)
- [x] 전역으로 저장한 현재 사용자 정보를 편리하게 가져오는 훅 생성
