### ISSUE TITLE
리덕스 툴킷 세팅하기

### ISSUE THREAD

**Issue by accguy** [TEAM-MUNA/muna#3]
## 💼 작업 설명
리덕스 툴킷 세팅하기

## ✅ To-do

- [x] 리덕스 툴킷 설치
- [ ] Redux Store 설정
- [ ] Redux Provider 설정
- [ ] Slice 생성
- [ ] 잘되는지 테스트
