### ISSUE TITLE
SCSS 세팅

### ISSUE THREAD

**Issue by page1597** [TEAM-MUNA/muna#5]
## 💼 작업 설명

SCSS 세팅을 한다.

## ✅ To-do

- [x] 컨벤션 정하기 : ex)변수명 input_icon
- [x] SCSS 설치
- [x] 기본 폴더 구조 생성 (main, variables, mixins, reset, ...)
- [x] 전역 스타일 설정
- [x] 믹스인 정의
- [x] 변수 정의
- [x] 전역 폰트 설정
