### ISSUE TITLE
로그인시, 바로 적용이 안되는 경우

### ISSUE THREAD

**Issue by diayeri** [TEAM-MUNA/muna#59]
## 💼 작업 설명
가끔 로그인시 바로 적용이 안되고, 새로고침을 해야 적용되는 경우가 있습니다.

## ✅ To-do
- [ ] 세팅페이지 리다이렉트 시, 최신 currentUser 정보 잘 가져오는지 확인
- [ ] 리다이렉트 조건 비교 시점 조정이 필요할지 확인
- [ ] 헤더가 currentUser 정보 잘 가져오는지 확인
- [ ] 로그인 관련 살펴보기
