### ISSUE TITLE
세팅 후 추가로 적용할 부분

### ISSUE THREAD

**Issue by diayeri** [TEAM-MUNA/muna#64]
## 💼 작업 설명
1. 프로필 수정 - 이미지, 아이디 (필수)
  - 이전에 작성한 리뷰목록에서는 이전정보로 나타나는 것 같음
2. 계정 삭제
  - 이전 작성한 리뷰는 삭제해야할까? (원래는 삭제하지만 없는 정보로라도 남겨두고 싶은데 안타깝다) -> 유지하자
3. 좋아요, 북마크 행위
  - 이전 활동시 좋아요, 북마크 했던 것 카운팅에서도 빼져야 할지 -> 둘다 상관없다! 남아도 상관없음 (북마크 배열에 아이디가 스트링으로 남을것)

## ✅ To-do
- [ ] 프로필 수정시, 이전에 작성한 리뷰정보에도 업데이트하기
- [ ] 계정 삭제시, 이전에 작성한 리뷰처리
- [ ] 계정 삭제시, 좋아요 북마크 수 변동여부 처리

**Comment by diayeri** [comment]
북마크나 후기등 작성했다가 삭제하면 어떻게 처리하는지도 정리 필요할지?

**Comment by diayeri** [comment]
firestore > reviews
<img width="353" alt="image" src="https://github.com/user-attachments/assets/8b1df29c-502a-4c40-af62-1318fac48f36">
