### ISSUE TITLE
공연 상세 > 제목 길어질때 처리

### ISSUE THREAD

**Issue by diayeri** [TEAM-MUNA/muna#65]
## 💼 작업 설명
제목이 길어지면 간격이 이상해져서 처리가 필요할것 같습니다 -> UI 고민요
<img width="383" alt="image" src="https://github.com/user-attachments/assets/8d007788-4a22-49e9-857f-51e73834184b">

## ✅ To-do
- [ ] 타이틀 2줄까지 생각해서 UI 조정 (저도 볼게요)
- [ ] 최대 2줄까지 보이게 스타일 수정 (믹스인 text_ellipsis)
- [ ] 최대 줄 외의 스타일 수정

**Comment by diayeri** [comment]
일단 타이틀 텍스트 사이즈 lg(16px)로 줄이고, 최대길이 2줄까지 보이게 처리해두면 될것같습니다.
<img width="381" alt="image" src="https://github.com/user-attachments/assets/60ba8842-2b1e-4ae9-932f-2750665ed359">
