### ISSUE TITLE
장르버튼 UI

### ISSUE THREAD

**Issue by diayeri** [TEAM-MUNA/muna#82]
## 💼 작업 설명
아래 두 페이지에 있는 장르버튼들을 한개의 컴포넌트 그룹으로 만들어도 좋을것 같습니다. (전체보기 있고없고는 props로 해도 좋을거 같아요)
1. 메인페이지 장르버튼이 모바일 기기에서 봤을때 사이즈, 비율 조정이 필요해보임 
(큰 화면에서 봤을때처럼 비율 되면 좋을듯, 안되면 레이아웃이 바뀌어도 화면 벗어나지 않도록 조정 필요)
<img width="397" alt="image" src="https://github.com/user-attachments/assets/44cdf60a-75e3-4581-a97c-a25983880c90">

2. 검색페이지 장르버튼 종류 업데이트 (위 메인과 동일하게)
<img width="401" alt="image" src="https://github.com/user-attachments/assets/fd0dd72f-b590-4f7c-bd70-24c2d481b010">

## ✅ To-do
- [ ] 메인페이지 장르버튼 사이즈/간격/레이아웃 벗어나지 않도록 수정
- [ ] 검색페이지 장르버튼도 종류, 스타일 맞추기
- [ ] 괜찮다면 한개의 컴포넌트로 정리

**Comment by diayeri** [comment]
GenreButtons 컴포넌트로 정리 완료
